name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: matt-ball/newman-action@v1.0.2
        with:
          collection: postman_collection.json
          environment: postman_environment.json