name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: matt-ball/newman-action@v1.0.2
        with:
          collection: https://raw.githubusercontent.com/arun-lmnas/blogs/main/postman_collection.json
          environment: https://raw.githubusercontent.com/arun-lmnas/blogs/main/postman_environment.json