name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@main
        with:
          collection: postman_collection.json